[phases.setup]
cmds = ["echo 'Setting up Go environment'"]

[phases.build]
cmds = [
  "go version",
  "go mod tidy",
  "go build -v -o out ."
]

[phases.start]
cmd = "./out"

[variables]
CGO_ENABLED = "0"
GOOS = "linux"